# -*- coding: utf-8 -*-
"""Módulo 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXaFI8NTJ68yJ1SEltYIDp4N6AN1UTsO
"""

def saudade():
  nome = input('Qual é o seu nome? ')
  print(f'Olá {nome}')

saudade()

"""# Parâmetros

"""

nome = 'Luiza'

def saudacao_com_parametros(nome_da_pessoa):
  print(f'Olá {nome_da_pessoa}')

saudacao_com_parametros(nome)

"""# Condicional"""

idade = 10
def verifica_se_pode_dirigir(idade):
  if idade >= 18:
    print('Tem permissão para dirigir')
  else:
    print('Não tem permisão para dirigir')

verifica_se_pode_dirigir(idade)

"""# Convertendo tipo para inteiro"""

def verifica_se_pode_dirigir_sem_parametros():
  idade = input('Qual a sua idade? ')
  idade = int(idade)
  if idade >= 18:
    print('Pode dirigir')
  else:
    print('Não pode dirigir')

verifica_se_pode_dirigir_sem_parametros()

def velocidade(espaco, tempo):
 # espaco = int(input('Qual é o tamanha do espaço percorrido? '))
  #tempo = int(input('Qual é o tempo até chegar ao local? '))
  velocidade_media = espaco/tempo
  return velocidade_media

velocidade(100, 20)

"""# Matplotlib"""

import matplotlib.pyplot as plt

x = list(range(1, 9))
y = [8,7,7,8,9,3,2,8]

plt.plot(x, y, marker = 'o')
plt.title('notas em matemática')
plt.xlabel('Provas')
plt.ylabel('Notas')
plt.show()

import matplotlib.pyplot as plt

notas_matematica = ['Matemática',8,7,6,6,7,7,8,10]
notas_portugues = ['Português',9,9,9,8,5,6,8,5]
notas_geografia = ['Geografia',10,10,6,7,7,7,8,7]

notas = [notas_matematica, notas_portugues, notas_geografia]

for nota in notas:
 x = list(range(1, 9))
 y = nota[1:]
 plt.plot(x, y, marker='o')
 plt.xlabel('Provas')
 plt.ylabel('Notas')
 plt.title(nota[0])
 plt.show()